image: docker:stable

variables:
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: "1"

services:
- docker:dind

before_script:
- docker info
- docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"


.build: &build
  stage: build
  only: &build-only
    changes:
    - Dockerfile
    - entrypoint.sh
    - nginx.conf
    - opcache.ini
    - scripts/*
    - wp-config.php
    - wp.sh
  script:
  - docker build .
    --pull=true
    --tag=${CI_REGISTRY_IMAGE}/${CI_JOB_NAME#build-}/build:${CI_PIPELINE_ID}
    ${TARGET+--target=$TARGET}
  after_script:
  - docker push
    ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME#build-}/build:${CI_PIPELINE_ID}

build-fastcgi:
  <<: *build
build-nginx:
  <<: *build
  variables:
    TARGET: nginx


.push-tags: &push-tags
  stage: deploy
  only:
    <<: *build-only
    refs: [master, develop]
  script: |
    BUILD_REPO=${CI_REGISTRY_IMAGE}/${CI_JOB_NAME#push-}/build:${CI_PIPELINE_ID}
    DEPLOY_REPO=${CI_REGISTRY_IMAGE}/${CI_JOB_NAME#push-}
    VERSION=`eval "docker run --rm ${BUILD_REPO} ${GET_VERSION}"`
    . scripts/deploy.sh

push-fastcgi:
  <<: *push-tags
  variables:
    GET_VERSION: wp core version
push-nginx:
  <<: *push-tags
  variables:
    GET_VERSION: nginx -V 2>&1 | sed -n '/nginx version:/s/.*nginx\///p'
