variables:
  WORDPRESS_VERSION:
    value: 6.0.3
    description: WordPress release
  PHP_VERSION:
    value: 8.1.11
    description: PHP release to build into the backend image
  NGINX_VERSION:
    value: 1.23.2
    description: Nginx release for the frontend image


workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    variables: {BUILD_RELEASE: "true"}
  - if: $CI_PIPELINE_SOURCE == "schedule"
    variables: {BUILD_RELEASE: "true"}
  - when: always


include:
- project: dom/project-templates
  file: /pipeline-templates/pre-commit.yml


Build Images:
  stage: build
  rules:
  - if: $BUILD_RELEASE
    when: never
  - if: $CI_PIPELINE_SOURCE == "web"
  - changes:
    - .gitlab-ci.yml
    - Dockerfile
    - data/*
    - plugins/*
    - scripts/*
  variables:
    PLATFORMS: ""
    BUILD_ARGS: >-
      wp_version=$WORDPRESS_VERSION
      php_version=$PHP_VERSION
      nginx_version=$NGINX_VERSION
  parallel:
    matrix:
    - TARGET: [nginx, fastcgi]
  trigger:
    include:
    - project: dom/project-templates
      file: /pipeline-templates/build-image.yml
    strategy: depend


Build Releases:
  stage: build
  extends: [Build Images]
  rules:
  - if: $BUILD_RELEASE
  parallel:
    matrix:
    - TARGET: [nginx]
      RELEASE: [$NGINX_VERSION]
    - TARGET: [fastcgi]
      RELEASE: [$WORDPRESS_VERSION]
