variables:
  WORDPRESS_VERSION:
    value: 5.8.1
    description: WordPress release
  PHP_VERSION:
    value: 8.0.0
    description: PHP release to build into the backend image
  NGINX_VERSION:
    value: 1.21.3
    description: Nginx release for the frontend image


.changes: &change-files
  changes:
  - .gitlab-ci.yml
  - Dockerfile
  - data/*
  - plugins/*
  - scripts/*

.build:
  stage: build
  image: docker.kodo.org.uk/ci-images/buildkit/buildctl:latest
  tags: [buildkit]
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - << : *change-files
  script:
  - BUILD_TAG=${CI_REGISTRY_IMAGE}/${TARGET}:build-${CI_PIPELINE_IID}
  - buildctl build
    --frontend=dockerfile.v0
    --local context=.
    --local dockerfile=.
    --opt target=${TARGET}
    --opt build-arg:nginx_version=${NGINX_VERSION}
    --opt build-arg:php_version=${PHP_VERSION}
    --opt build-arg:wp_version=${WORDPRESS_VERSION}
    --opt label:nginx.version=${NGINX_VERSION}
    --opt label:php.version=${PHP_VERSION}
    --opt label:wordpress.version=${WORDPRESS_VERSION}
    --output type=image,name=${BUILD_TAG},push=true


.tag:
  stage: deploy
  image: docker.kodo.org.uk/ci-images/docker-reg:latest
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"
    variables:
      TAG: latest
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    << : *change-files
    variables:
      TAG: latest
  - if: $CI_COMMIT_BRANCH == "develop"
    << : *change-files
    variables:
      TAG: unstable
  script: |
    BUILD_TAG=${CI_REGISTRY_IMAGE}/${TARGET}:build-${CI_PIPELINE_IID}
    docker-reg $BUILD_TAG retag $TAG
    if [ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]; then
      docker-reg $BUILD_TAG retag $VERSION
    fi


Build Wordpress:
  extends: [.build]
  variables:
    TARGET: fastcgi

Build Nginx:
  extends: [.build]
  variables:
    TARGET: nginx


Tag Wordpress Image:
  extends: [.tag]
  variables:
    TARGET: fastcgi
    VERSION: $WORDPRESS_VERSION

Tag Nginx Image:
  extends: [.tag]
  variables:
    TARGET: nginx
    VERSION: $NGINX_VERSION
