#!/bin/bash
set -eu

# constants
WP_ROOT=${WORDPRESS_ROOT:-/var/www/html}
WP_CONTENT=${WP_ROOT}/wp-content
WP_CONFIG=${WP_ROOT}/wp-config.php

die() { echo "$*" >&2; exit 1; }

genkey() { head -c1M /dev/urandom | sha1sum | cut -d' ' -f1; }

create_config()
{
cat > $WP_CONFIG <<END_CONFIG
<?php
/**
 * Generated by entrypoint.sh
 * `date`
 */

define('DB_HOST', '${DB_HOST}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASSWORD', '${DB_PASSWORD}');

define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

\$table_prefix = 'wp_';

define('AUTH_KEY',         '`genkey`');
define('SECURE_AUTH_KEY',  '`genkey`');
define('LOGGED_IN_KEY',    '`genkey`');
define('NONCE_KEY',        '`genkey`');
define('AUTH_SALT',        '`genkey`');
define('SECURE_AUTH_SALT', '`genkey`');
define('LOGGED_IN_SALT',   '`genkey`');
define('NONCE_SALT',       '`genkey`');

define('FS_METHOD', 'direct');

define('WP_DEBUG', false);
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

require_once(ABSPATH . 'wp-settings.php');
END_CONFIG
}

run_setup()
{
	# setup entrypoint
	# ----------------
	# Setup the database, install the scripts & make a config
	
	source /etc/wordpress/mysql.conf

	# parse command line arguments
	SHIFT=shift
	POP='"$2"; SHIFT=shift; shift'
	while [ $# -gt 0 ]; do
		case "$1" in
			--*=*)
				set ${1%%=*} ${1#*=} "${@:2}"
				continue
				;;
			-*)
				set ${1:0:2} ${1#??} "${@:2}"
				# SHIFT adds the character-option hyphen onto $2 if is not POPed
				# as an argument first.
				SHIFT='set -$2 "${@:3}"; SHIFT=shift'
				continue
				;;

			-h|--host) exec DB_HOST=$POP ;;
			-d|--database) exec DB_NAME=$POP ;;
			-u|--user) exec DB_USER=$POP ;;
			-p|--password) exec DB_PASSWORD=$POP ;;
		esac
		$SHIFT
	done

	# command line argument defaults
	: ${DB_HOST:=mysql}
	: ${DB_USER:="${DB_NAME?A database name is required}_user"}
	: ${DB_PASSWORD:=}

	create_config
}

run_install()
{
	# overwrite current source onto deployed scripts
	rm -r /usr/src/wordpress/wp-content/
	cp -r /usr/src/wordpress/* ${WP_ROOT}/
	mkdir -p ${WP_CONTENT}
	# prevent core scripts from being overwritten by the application.
	chown -R root:root ${WP_ROOT}/
	# allow themes, plugins & content to be installed/managed by the application
	chown -R www-data:www-data ${WP_CONTENT}
}

run_cmd()
{
	# main entrypoint
	# ---------------
	# Run the given command after sanity checks

	# install/upgrade to volume from image source
	run_install
	# run setup entrypoint if it has not been run on this container before
	test -e $WP_CONFIG || run_setup
	# exec the command
	exec "$@"
}

case "$1" in
	setup) run_install && shift && run_setup "$@" ;;
	*) run_cmd "$@" ;;
esac
