apiVersion: v1
kind: Service

metadata:
  name: wordpress

spec:
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: SITE_URL
  ports:
  - name: http
    protocol: TCP
    port: 80
